### ISSUE TITLE
Error creating machine

### ISSUE THREAD

**Issue by julianboehne** [JonasProgrammer/docker-machine-driver-hetzner#114]
Hello,
I used this driver on different autoscaling images like [this one](https://github.com/N4Y-docker/gitlab-runner-machine-hetzner). I'm running Docker on my Windows system locally and an error occurs when i try the command:

```
docker-machine create \
  --driver hetzner \
  --hetzner-api-token=******** \
  --hetzner-server-location=fsn1 \
  --hetzner-image=ubuntu-22.04 \
  --hetzner-server-type=cx11 \
  GitLab-Docker-Machine
``` 

The server is starting on the Hetzner Cloud but i get this ssh-error:

```
Error creating machine: Error running provisioning: Error running "DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y  curl": ssh command error:
command : DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y  curl
err     : exit status 255
```

I also tried to connect to the server inside the docker container and this works well with ssh.
What can I do?

**Comment by JonasProgrammer** [comment]
Hi, the exit status comes from the commands run by `docker-machine` to provision an already existing server, i.e. the driver has nothing to do with this.

Can you try runnning `DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y  curl` directly on the working SQL connection? Perhaps you'll get more error output then.

**Comment by julianboehne** [comment]
Alright, I tested the command directly with ssh and it works well. I searched this command in the docker-machine repo and I found it there. But why does this command works well using ssh and failed with the docker-machine.
When I try to debug in docker with _docker-machine -D_, I get following new error:
```
About to run SSH command:

                if ! grep -xq '.*\sGitLab-Docker-Machine' /etc/hosts; then
                        if grep -xq '127.0.1.1\s.*' /etc/hosts; then
                                sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 GitLab-Docker-Machine/g' /etc/hosts;
                        else 
                                echo '127.0.1.1 GitLab-Docker-Machine' | sudo tee -a /etc/hosts; 
                        fi
                fi
SSH cmd err, output: <nil>:
```

**Comment by JonasProgrammer** [comment]
Very strange indeed.

Can you perhaps try `docker-machine ssh` after the server was created? You don't actually need to wait for the provisioning process to fail, just don't kill it right after creation (waiting for the next output after 'Waiting for the server to come up' should be fine).
Despite not being provisioned, the machine's access credentials etc. should be available at this stage, so `docker-machine ssh` should work (fingers crossed).

If the command were to run successful even then, I'm out of ideas right now. I have seen a fair share of driver-related stuff, but heisenbugs in regards to seemingly simple shell commands are a first...

**Comment by julianboehne** [comment]
No more ideas,

I stopped the creating process before the `Detecting the provisioner...` step. I tried the `docker-machine ssh` command and everything works fine. Thanks for the great help, but at the moment I don't have any new ideas to fix this issue.

**Comment by mrjackv** [comment]
@julianboehne I've encountered the same issue yesterday as well and figured out the problem
It's a combination of:
* **Many** servers (~100) trying to brute force the ssh password
* The default ssh `MaxStartups` being set relatively low (`10:30:100`)

That means that every time `docker-machine` tries to issue a command it via ssh there's a good chance it'll be dropped
I've "solved" the problem by using the following `cloud-init`:
```yaml
#cloud-config
package_update: true
packages:
  - fail2ban
bootcmd:
  # Temporarely disable ssh, otherwise docker-machine will try to install
  # its stuff before we're done running the cloud-init
  - systemctl disable --now ssh.service
write_files:
- path: /etc/fail2ban/jail.local
  content: |
    [sshd]
    enabled = true
    mode = aggressive
- path: /etc/ssh/sshd_config.d/custom.conf
  content: |
    MaxStartups 300:30:1000
    PasswordAuthentication no
runcmd:
  - systemctl enable --now fail2ban.service
  - systemctl enable --now ssh.service
  ```
